### PR TITLE
more tags + alphabetical listing

### PR DESCRIPTION
**Pull request by antoinefalisse**
I have added a few tags and listed them all by alphabetical order (label). What do you think?

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
Looking good and working perfectly for me. I think the one that can better assess this PR is Matt, as he was working on unify tags between OpenCap and AddBiomechanics.

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM! Once Matt confirms if everything is alright, we can merge.

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse I've talked with Matt and we have a question:

What "Right Leg" and "Left Leg" stand for? is is right or leg single squat? Is it standing on a single leg? Or something generic to refer to an arbitrary action with either leg?

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz

> Or something generic to refer to an arbitrary action with either leg?
Yes that's what I meant. You could associate it with like squats, or countermovement jumps, or any type of jumps for instance. In rehab/sports, people often distinguish between double-leg and single-leg activities. It would be great if we could capture that in our datasets, and this might be a way to do it. I'm open to suggestions. Maybe we should also add dominant and non-dominant.

something like that if people do it with a single leg.

**Comment by AlbertoCasasOrtiz** [comment]
Sounds good to me. I've talked with Matt and we both think having dominant and non-dominant would be good. 

If you add it, I think you can directly merge then

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz see last commit. Feel free to merge.

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM! Approve and merge

**Pull request merged**
