### PR TITLE
add squat analysis dashboard

### PR DESCRIPTION
**Pull request by carmichaelong**

### CODE REVIEW

**Comment by antoinefalisse** [comment]
@carmichaelong awesome. Is there a way to make this more general, less squat-focused, so that it can be re-used? I guess you will want to use something similar for dropjump for instance, but I'm not sure it is great practice to start having lots of activity/project-specific scripts. Instead of hard coding for instance "Detected squat type", could you pass it through the json file, and have the ui script as just a different type of plot (like mean_std or something like that)?

**Comment by carmichaelong** [comment]
You brought up two issues that I think we can consider separately:

> Is there a way to make this more general, less squat-focused, so that it can be re-used? I guess you will want to use something similar for dropjump for instance, but I'm not sure it is great practice to start having lots of activity/project-specific scripts.

This is a more general question on the goals of the dashboards. If we want slightly different text for certain motions (e.g., a squat could be double-leg or single-leg), then that would need to have some info provided up top, or a separate analysis (e.g., a single-leg squat and a double-leg squat). In particular, another layout might be needed for the dropjumps later if user input is needed to denote the dominant leg to calculate contact time periods (e.g., you could pre-calculate for either leg as dominant, and then using a drop-down menu, the user could select left or right and update the metrics to reflect that).

In this case (squats), perhaps a few possible ways to work around:
1. Have an option to provide metadata header and text (similar to the metrics). The headers and text would share font styles (like metrics do).
2. Create a separate .vue for printing text like metadata. Then, use that as another piece to fit into the dashboard (and keep the scalar metrics +/- in a different .vue)
3. Don't provide double-leg or single-leg information. This would defer any decisions here (and still OK for the target goals this summer)

> Instead of hard coding for instance "Detected squat type", could you pass it through the json file, and have the ui script as just a different type of plot (like mean_std or something like that)?

That's a good idea. For sure this could be in the json file instead.

**Comment by carmichaelong** [comment]
@antoinefalisse thanks for chatting. updated PR to avoid hard coding the info about squat type.

**Review by antoinefalisse — APPROVED** [review]
Looks good, please just change back main.js for deployment.

**Comment by carmichaelong** [comment]
Oops, thanks for catching that! Reverted now and will merge

**Pull request merged**
