### PR TITLE
Changed steps name for something meaningful

### LINKED ISSUE #231: Change names of steps to something more meaningful
I've noticed we are still using "Step n" names in code an URLs.

Should we change it to names more meaningful? For example, Step 1 could be "connect_phones", Step 2 could be "calibration" and Step 4 could be "neutral pose".

I think it could be confusing having in the URLs Step 1, Step 2 and Step 4, when Step 3 is not used, and Step 5 is session view.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Closes #231.

Changed names to:

- [x] Step1 - Connect Devices (connect-devices)
- [x] Step2 - Calibration (calibration)
- [x] Step3 - _Removed from code_
- [x] Step4 - Neutral (neutral)
- [x] Step5 - Session (session)

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse I just fixed conflicts here, you can test now (no priority for this one)

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse I just solved latest conflicts here.

**Comment by antoinefalisse** [comment]
I will try to get to that this week, thanks and sorry for being slow.

**Comment by AlbertoCasasOrtiz** [comment]
Thank you! Don't worry, this is nothing blocking or prioritary

**Comment by AlbertoCasasOrtiz** [comment]
I reviewing open PRs for conflicts and I just solved conflicts here!

**Pull request merged**
